# Generated by Django 2.1.7 on 2020-07-09 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0002_auto_20200707_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='easyquestionanwers',
            name='level',
            field=models.CharField(default='easy', max_length=250),
        ),
        migrations.AddField(
            model_name='hardquestionanwers',
            name='level',
            field=models.CharField(default='hard', max_length=250),
        ),
        migrations.AddField(
            model_name='mediumquestionanwers',
            name='level',
            field=models.CharField(default='medium', max_length=250),
        ),
    ]
