# Generated by Django 2.1.7 on 2020-07-11 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0003_auto_20200709_1917'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Do ensure to not make spelling mistakes as certificates cannot be reissued.', max_length=250, verbose_name='Name to be written on certificate')),
                ('email', models.EmailField(help_text='Do ensure to give proper email address without any errors.', max_length=250, verbose_name='Email Id where certificate could be sent')),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='quiz',
            name='fail_text',
            field=models.TextField(blank=True, default="Hey, you were not able to pass this time. But don't lose hope. Work hard and come with a bang next time.", help_text='Displayed if user fails. [Optional]', verbose_name='Fail Text'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='success_text',
            field=models.TextField(blank=True, default='Hey, you successfully passed the quiz. It was difficult but you indeed succeeded. Congratulations and wish you more success!!!.', help_text='Displayed if user passes. [Optional]', verbose_name='Success Text'),
        ),
    ]
