# Generated by Django 2.1.7 on 2020-07-11 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0004_auto_20200711_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_detail',
            name='marks_obtained',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user_detail',
            name='status',
            field=models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail')], default='fail', max_length=250),
        ),
    ]
