# Generated by Django 2.1.7 on 2020-07-11 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0005_auto_20200711_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_detail',
            name='marks_obtained',
            field=models.SmallIntegerField(default=0, null=True),
        ),
    ]
