# Generated by Django 2.1.7 on 2020-07-11 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0006_auto_20200711_1335'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_Detail',
        ),
    ]
