# Generated by Django 2.1.7 on 2020-07-21 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0008_user_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='easyquestionanwers',
            name='answers',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='easyquestionanwers',
            name='option_5',
            field=models.TextField(blank=True, default='', help_text='Enter option 5. If not required, then skip and leave the field blank.', verbose_name='Type Option 5'),
        ),
        migrations.AddField(
            model_name='easyquestionanwers',
            name='type_of_quiz',
            field=models.CharField(choices=[('single', 'Single Correct Answer'), ('multiple', 'Multiple Correct Answer')], default='single', max_length=250),
        ),
        migrations.AlterField(
            model_name='easyquestionanwers',
            name='answer',
            field=models.CharField(choices=[('1', 'Option 1'), ('2', 'Option 2'), ('3', 'Option 3'), ('4', 'Option 4'), ('5', 'Option 5')], default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='easyquestionanwers',
            name='option_1',
            field=models.TextField(help_text='Enetr option 1. This field has to be filled compulsorily.', verbose_name='Type Option 1'),
        ),
        migrations.AlterField(
            model_name='easyquestionanwers',
            name='option_2',
            field=models.TextField(blank=True, help_text='Enter option 2. This field has to be filled compulsorily.', verbose_name='Type Option 2'),
        ),
        migrations.AlterField(
            model_name='easyquestionanwers',
            name='option_3',
            field=models.TextField(blank=True, default='', help_text='Enter option 3. If not required, then skip and leave the field blank.', verbose_name='Type Option 3'),
        ),
        migrations.AlterField(
            model_name='easyquestionanwers',
            name='option_4',
            field=models.TextField(blank=True, default='', help_text='Enter option 4. If not required, then skip and leave the field blank.', verbose_name='Type Option 4'),
        ),
    ]
