# Generated by Django 2.1.7 on 2020-07-21 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0010_auto_20200721_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='easyquestionanwers',
            name='answer',
            field=models.CharField(blank=True, choices=[('1', 'Option 1'), ('2', 'Option 2'), ('3', 'Option 3'), ('4', 'Option 4'), ('5', 'Option 5')], max_length=250),
        ),
    ]
