# Generated by Django 2.1.7 on 2020-07-22 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0011_auto_20200721_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='hardquestionanwers',
            name='answers',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='hardquestionanwers',
            name='option_5',
            field=models.TextField(blank=True, default='', help_text='Enter option 5. If not required, then skip and leave the field blank.', verbose_name='Type Option 5'),
        ),
        migrations.AddField(
            model_name='hardquestionanwers',
            name='type_of_quiz',
            field=models.CharField(choices=[('single', 'Single Correct Answer'), ('multiple', 'Multiple Correct Answers')], default='single', max_length=250),
        ),
        migrations.AddField(
            model_name='mediumquestionanwers',
            name='answers',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='mediumquestionanwers',
            name='option_5',
            field=models.TextField(blank=True, default='', help_text='Enter option 5. If not required, then skip and leave the field blank.', verbose_name='Type Option 5'),
        ),
        migrations.AddField(
            model_name='mediumquestionanwers',
            name='type_of_quiz',
            field=models.CharField(choices=[('single', 'Single Correct Answer'), ('multiple', 'Multiple Correct Answers')], default='single', max_length=250),
        ),
        migrations.AlterField(
            model_name='easyquestionanwers',
            name='type_of_quiz',
            field=models.CharField(choices=[('single', 'Single Correct Answer'), ('multiple', 'Multiple Correct Answers')], default='single', max_length=250),
        ),
        migrations.AlterField(
            model_name='hardquestionanwers',
            name='answer',
            field=models.CharField(blank=True, choices=[('1', 'Option 1'), ('2', 'Option 2'), ('3', 'Option 3'), ('4', 'Option 4')], max_length=250),
        ),
        migrations.AlterField(
            model_name='hardquestionanwers',
            name='option_1',
            field=models.TextField(help_text='Enetr option 1. This field has to be filled compulsorily.', verbose_name='Type Option 1'),
        ),
        migrations.AlterField(
            model_name='hardquestionanwers',
            name='option_2',
            field=models.TextField(blank=True, help_text='Enter option 2. This field has to be filled compulsorily.', verbose_name='Type Option 2'),
        ),
        migrations.AlterField(
            model_name='hardquestionanwers',
            name='option_3',
            field=models.TextField(blank=True, default='', help_text='Enter option 3. If not required, then skip and leave the field blank.', verbose_name='Type Option 3'),
        ),
        migrations.AlterField(
            model_name='hardquestionanwers',
            name='option_4',
            field=models.TextField(blank=True, default='', help_text='Enter option 4. If not required, then skip and leave the field blank.', verbose_name='Type Option 4'),
        ),
        migrations.AlterField(
            model_name='mediumquestionanwers',
            name='answer',
            field=models.CharField(blank=True, choices=[('1', 'Option 1'), ('2', 'Option 2'), ('3', 'Option 3'), ('4', 'Option 4')], max_length=250),
        ),
        migrations.AlterField(
            model_name='mediumquestionanwers',
            name='option_1',
            field=models.TextField(help_text='Enetr option 1. This field has to be filled compulsorily.', verbose_name='Type Option 1'),
        ),
        migrations.AlterField(
            model_name='mediumquestionanwers',
            name='option_2',
            field=models.TextField(blank=True, help_text='Enter option 2. This field has to be filled compulsorily.', verbose_name='Type Option 2'),
        ),
        migrations.AlterField(
            model_name='mediumquestionanwers',
            name='option_3',
            field=models.TextField(blank=True, default='', help_text='Enter option 3. If not required, then skip and leave the field blank.', verbose_name='Type Option 3'),
        ),
        migrations.AlterField(
            model_name='mediumquestionanwers',
            name='option_4',
            field=models.TextField(blank=True, default='', help_text='Enter option 4. If not required, then skip and leave the field blank.', verbose_name='Type Option 4'),
        ),
    ]
