# Generated by Django 2.1.7 on 2020-07-23 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0012_auto_20200722_1224'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.DurationField()),
            ],
        ),
        migrations.AlterField(
            model_name='quiz',
            name='time_alloted',
            field=models.DurationField(help_text='Time to be alloted for Quiz.', verbose_name='Time Alloted'),
        ),
    ]
