# Generated by Django 2.1.7 on 2020-07-23 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0013_auto_20200723_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='time_alloted',
            field=models.CharField(help_text='Time to be alloted for Quiz.', max_length=250, verbose_name='Time Alloted'),
        ),
    ]
