# Generated by Django 2.1.7 on 2020-07-23 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0015_quiz_ready_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='max_questions',
            field=models.PositiveIntegerField(help_text='Number of questions to be asked on each attempt. [Optional]', null=True, verbose_name='Max Questions'),
        ),
    ]
