# Generated by Django 2.1.7 on 2020-07-23 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0016_auto_20200723_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardquestionanwers',
            name='answer',
            field=models.CharField(blank=True, choices=[('1', 'Option 1'), ('2', 'Option 2'), ('3', 'Option 3'), ('4', 'Option 4'), ('5', 'Option 5')], max_length=250),
        ),
        migrations.AlterField(
            model_name='mediumquestionanwers',
            name='answer',
            field=models.CharField(blank=True, choices=[('1', 'Option 1'), ('2', 'Option 2'), ('3', 'Option 3'), ('4', 'Option 4'), ('5', 'Option 5')], max_length=250),
        ),
    ]
